set timeout 30

send_user "\n\nStart to login to the test bed...\n\n"

spawn /usr/bin/ssh  [lindex $argv 0]@[lindex $argv 1]
expect "@murano"
send -- "sudo su\n"
expect "@murano"
send -- "sed -i \"s/#amqp_durable_queues=false/amqp_durable_queues=false/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/#amqp_auto_delete=false/amqp_auto_delete=false/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/#rabbit_host=localhost/rabbit_host="
send -- [lindex $argv 2]
send -- "/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/#rabbit_port=5672/rabbit_port="
send -- [lindex $argv 3]
send -- "/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i 's/#\\(rabbit_hosts=.*\\)/\\1/' /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/#rabbit_use_ssl=false/rabbit_use_ssl="
send -- [lindex $argv 4]
send -- "/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/#rabbit_userid=guest/rabbit_userid="
send -- [lindex $argv 5]
send -- "/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/#rabbit_password=guest/rabbit_password=swordfish/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/#rabbit_virtual_host=\\//rabbit_virtual_host="
send -- [lindex $argv 5]
send -- "/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/#rabbit_retry_interval=1/rabbit_retry_interval=1/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/#rabbit_retry_backoff=2/rabbit_retry_backoff=2/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/#rabbit_max_retries=0/rabbit_max_retries=0/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/#rabbit_ha_queues=false/rabbit_ha_queues=false/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/auth_host = 127.0.0.1/auth_host = "
send -- [lindex $argv 2]
send -- "/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/connection = sqlite:\\/\\/\\/\\/etc\\/murano\\/murano-api.sqlite/connection = mysql:\\/\\/murano:swordfish@localhost:3306\\/murano/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "sed -i \"s/auth_url = http:\\/\\/localhost:5000\\/v2.0/auth_url = http:\\/\\/"
send -- [lindex $argv 2]
send -- ":5000\\/v2.0/\" /etc/murano/murano.conf\n"
expect "@murano"
send -- "murano-manage --config-file /etc/murano/murano.conf db-sync\n"
expect "@murano"
send -- "service murano-api restart\n"
expect "@murano"
send -- "service murano-engine restart\n"
expect "@murano"
